name: Repository Security Check

on:
  workflow_call:
    outputs:
      should-run:
        description: "Whether the workflow should continue"
        value: ${{ jobs.check-repo.outputs.should-run }}

permissions:
  contents: read

jobs:
  check-repo:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      should-run: ${{ steps.validate.outputs.should-run }}

    steps:
      - name: Validate repository
        id: validate
        run: |
          if [[ "${{ github.repository }}" == "Malldre/Github-Actions" ]]; then
            echo "## ⛔ Workflow Execution Blocked" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "❌ This workflow cannot run in the source repository (\`Malldre/Github-Actions\`)." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "These workflows are designed to be **used by other repositories**, not executed here." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "If you need to test workflows, please:" >> $GITHUB_STEP_SUMMARY
            echo "1. Create a test repository" >> $GITHUB_STEP_SUMMARY
            echo "2. Call these workflows from there" >> $GITHUB_STEP_SUMMARY
            
            echo "should-run=false" >> $GITHUB_OUTPUT
            echo "❌ Workflow execution blocked - running in source repository"
            exit 1
          else
            echo "## ✅ Repository Check Passed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
            echo "**Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
            echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "✅ Repository validation successful - workflow can proceed safely."
            
            echo "should-run=true" >> $GITHUB_OUTPUT
          fi

      - name: Additional security checks
        if: steps.validate.outputs.should-run == 'true'
        run: |
          echo "🔍 Running additional security validations..."

          # Check if running in a fork
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" && "${{ github.event.pull_request.head.repo.full_name }}" != "" ]]; then
            echo "⚠️ Warning: Running in a forked repository"
            echo "Fork: ${{ github.event.pull_request.head.repo.full_name }}"
          fi

          # Check repository owner
          REPO_OWNER="${{ github.repository_owner }}"
          echo "✅ Repository owner: $REPO_OWNER"

          # Verify this is not a template repository event
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "ℹ️ Triggered via repository_dispatch event"
          fi

          echo "✅ All security checks passed"
