name: Repository Security Check

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-repo:
    # Prevent execution in the workflows repository itself
    if: github.repository != 'Malldre/Github-Actions'
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Repository validation passed
        run: |
          echo "## ✅ Repository Check Passed" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Branch:** \`${{ github.ref_name }}\`" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** ${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "✅ Repository validation successful - workflow can proceed safely."

      - name: Additional security checks
        run: |
          echo "🔍 Running additional security validations..."

          # Check if running in a fork
          if [[ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" && "${{ github.event.pull_request.head.repo.full_name }}" != "" ]]; then
            echo "⚠️ Warning: Running in a forked repository"
            echo "Fork: ${{ github.event.pull_request.head.repo.full_name }}"
          fi

          # Check repository owner
          REPO_OWNER="${{ github.repository_owner }}"
          echo "✅ Repository owner: $REPO_OWNER"

          # Verify this is not a template repository event
          if [[ "${{ github.event_name }}" == "repository_dispatch" ]]; then
            echo "ℹ️ Triggered via repository_dispatch event"
          fi

          echo "✅ All security checks passed"

  # This job will always run to show why the check was skipped
  check-skipped-notification:
    if: github.repository == 'Malldre/Github-Actions'
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Workflow skipped in source repository
        run: |
          echo "## ℹ️ Workflow Check Skipped" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Repository:** \`${{ github.repository }}\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "This workflow is designed to run only in repositories that **use** these reusable workflows." >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "Since this is the source repository (\`Malldre/Github-Actions\`), the check is skipped." >> $GITHUB_STEP_SUMMARY
          echo "This is expected behavior and not an error." >> $GITHUB_STEP_SUMMARY

          echo "ℹ️ Check skipped - running in source repository (Malldre/Github-Actions)"
          echo "This is expected and not an error."
